---
apiVersion: v1
kind: Service
metadata:
    name: lb01
    labels:
      app: lb01
    namespace: default
spec:
    selector:
      postgres-operator.crunchydata.com/cluster: hippo
      postgres-operator.crunchydata.com/role: master
    type: LoadBalancer
    ports:
      - port: 5432
        targetPort: 5432
        protocol: TCP
status:
  loadBalancer:
    ingress:
    - ip: ""
