apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: s3-secret
  files:
  - AWS_ACCESS_KEY_ID
  - AWS_SECRET_ACCESS_KEY
resources:
- minio.yml
generatorOptions:
  disableNameSuffixHash: true
