apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pv-csi-claim
  namespace: default
  labels:
    app: minio-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: csi
