apiVersion: v1
kind: ServiceAccount
metadata:
  name: azure-test-sa-cms-bff
  namespace: cms-bff
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: azure-role-test-binding-cms-bff
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: azure-cluster-test-role
subjects:
- apiGroup: ""
  kind: ServiceAccount
  name: azure-test-sa-cms-bff
  namespace: cms-bff
